import type { Metadata } from "next";
// import "./globals.css";

import BoxFastBooking from "@/components/cinematic/BoxFastBooking";
import ShowingMovie from "@/components/book/ShowingMovie";
import ButtonWatchMore from "@/components/common/ButtonWatchMore";
import DescriptionCinematic from "@/components/cinematic/DescriptionCinematic";
import apiMovie from "@/apis/movie";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(
  {
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>,
  searchParams: {
    searchParams: { [key: string]: string | string[] | undefined };
  }
) {
  // const genresData = apiGenre.getListGenres();
  const moviesData = apiMovie.getListMovie(searchParams);

  const moviesShowingData = apiMovie.getListMovie({ status: "showing" });

  const [movies, moviesShowing] = await Promise.all([
    moviesData,
    moviesShowingData,
  ]);

  return (
    <>
      <div className="flex gap-6 w-main mx-auto pb-[50px] mt-10">
        <div className="flex-7">{children}</div>

        <div className="flex-3">
          <BoxFastBooking movies={movies?.data?.rows} />

          <ShowingMovie data={moviesShowing?.data?.rows} />

          <div className="flex justify-end mt-4">
            <ButtonWatchMore />
          </div>
        </div>
      </div>

      <DescriptionCinematic />
    </>
  );
}
